package info.blockchain.wallet.metadata;

import info.blockchain.api.MetadataEndpoints;
import info.blockchain.wallet.metadata.data.Auth;
import info.blockchain.wallet.metadata.data.Invitation;
import info.blockchain.wallet.metadata.data.Message;
import info.blockchain.wallet.metadata.data.Status;
import info.blockchain.wallet.metadata.data.Trusted;
import info.blockchain.wallet.util.MetadataUtil;

import org.apache.commons.codec.binary.Base64;
import org.bitcoinj.crypto.DeterministicKey;
import org.bitcoinj.params.MainNetParams;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

import okhttp3.OkHttpClient;
import okhttp3.logging.HttpLoggingInterceptor;
import retrofit2.Call;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class MetadataShared {

    private MetadataEndpoints endpoints;
    private String token;
    private String publicXpub;
    private String address;
    private DeterministicKey node;

    public MetadataShared(DeterministicKey masterHDNode) throws Exception {

        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client = new OkHttpClient.Builder().addInterceptor(interceptor).build();

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(MetadataEndpoints.API_URL)
//                .client(client)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        endpoints = retrofit.create(MetadataEndpoints.class);

        setMetadataNode(masterHDNode);
        this.token = getToken();
    }

    /**
     * Set shared metadata node and address
     * Set encryption key:
     * purpose' / type' / 0' : https://meta.blockchain.info/{address} - signature used to authenticate
     * purpose' / type' / 1' : sha256(private key) used as 256 bit AES key
     * @param masterHDNode
     * @throws Exception
     */
    private void setMetadataNode(DeterministicKey masterHDNode) throws Exception{

        int purpose = MetadataUtil.getPurpose();

        DeterministicKey metaDataHDNode = MetadataUtil.deriveHardened(masterHDNode, purpose);

        this.address = metaDataHDNode.toAddress(MainNetParams.get()).toString();
        this.node = metaDataHDNode;
        this.publicXpub = metaDataHDNode.serializePubB58(MainNetParams.get());
        // TODO: 23/11/16 Publish xpub
    }

    /**
     * @return address
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Get nonce generated by the server (auth challenge).
     */
    private String getNonce() throws Exception {

        Call<Auth> response = endpoints.getNonce();

        Response<Auth> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body().getNonce();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Get JSON Web Token if signed nonce is correct. Signed.
     */
    protected String getToken() throws Exception {

        String nonce = getNonce();
        String sig = node.signMessage(nonce);

        HashMap<String, String> map = new HashMap<>();
        map.put("mdid", address);
        map.put("signature", sig);
        map.put("nonce", nonce);
        Call<Auth> response = endpoints.getToken(map);

        Response<Auth> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body().getToken();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Get list of all trusted MDIDs. Authenticated.
     */
    public Trusted getTrustedList() throws Exception {

        Call<Trusted> response = endpoints.getTrustedList("Bearer " + token);

        Response<Trusted> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Check if a contact is on trusted list of mdid. Authenticated.
     */
    public boolean getTrusted(String mdid) throws Exception {

        Call<Trusted> response = endpoints.getTrusted("Bearer " + token, mdid);

        Response<Trusted> exe = response.execute();

        if (exe.isSuccessful()) {
            return Arrays.asList(exe.body().getContacts()).contains(mdid);
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Add a contact to trusted list of mdid. Authenticated.
     */
    public boolean putTrusted(String mdid) throws Exception {

        Call<Trusted> response = endpoints.putTrusted("Bearer " + token, mdid);

        Response<Trusted> exe = response.execute();

        if (exe.isSuccessful()) {
            return mdid.equals(exe.body().getContact());
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Delete a contact from trusted list of mdid. Authenticated.
     */
    public boolean deleteTrusted(String mdid) throws Exception {

        Call<Status> response = endpoints.deleteTrusted("Bearer " + token, mdid);

        Response<Status> exe = response.execute();

        if (exe.isSuccessful()) {
            return true;
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }


    /**
     * Add new shared metadata entry. Signed. Authenticated.
     */
    public Message postMessage(String mdid, String message, int type) throws Exception {

        String encryptedMessage = encryptFor(message, mdid);

        String b64Msg = new String(Base64.encodeBase64String(encryptedMessage.getBytes()));

        String signature = node.signMessage(b64Msg);

        Message request = new Message();
        request.setRecipient(mdid);
        request.setType(type);
        request.setPayload(b64Msg);
        request.setSignature(signature);

        Call<Message> response = endpoints.postMessage("Bearer " + token, request);

        Response<Message> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }

    }

    private String encryptFor(String message, String mdid) throws Exception {

        return message;
    }

    /**
     * Get messages sent to my MDID. Authenticated.
     */
    public List<Message> getMessages(boolean onlyProcessed) throws Exception {

        Call<List<Message>> response = endpoints.getMessages("Bearer " + token, onlyProcessed);

        Response<List<Message>> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Get messages sent to my MDID. Authenticated.
     */
    public List<Message> getMessages(String lastMessageId) throws Exception {

        Call<List<Message>> response = endpoints.getMessages("Bearer " + token, lastMessageId);

        Response<List<Message>> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Get message from message id. Authenticated.
     */
    public Message getMessage(String messageId) throws Exception {

        Call<Message> response = endpoints.getMessage("Bearer " + token, messageId);

        Response<Message> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Obtains a one-time UUID for key sharing Gets MDID of sender from one-time UUID
     */
    public Invitation createInvitation() throws Exception {

        Call<Invitation> response = endpoints.postShare("Bearer " + token);

        Response<Invitation> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Sets the MDID of the recipient
     */
    public Invitation acceptInvitation(String uuid) throws Exception {

        Call<Invitation> response = endpoints.postToShare("Bearer " + token, uuid);

        Response<Invitation> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Gets MDID of sender from one-time UUID
     */
    public Invitation readInvitation(String uuid) throws Exception {

        Call<Invitation> response = endpoints.getShare("Bearer " + token, uuid);

        Response<Invitation> exe = response.execute();

        if (exe.isSuccessful()) {
            return exe.body();
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }

    /**
     * Deletes one-time UUID
     */
    public boolean deleteInvitation(String uuid) throws Exception {

        Call<Invitation> response = endpoints.deleteShare("Bearer " + token, uuid);

        Response<Invitation> exe = response.execute();

        if (exe.isSuccessful()) {
            return true;
        } else {
            throw new Exception(exe.code() + " " + exe.message());
        }
    }
}